### ISSUE TITLE
Calling player.load(...) opens safari instead of loading the video

### ISSUE THREAD

**Issue by L4grange** [youtube/youtube-ios-player-helper#374] opened 2020-05-12 08:50 UTC
I've tried using the master branch in my pod in order to get the recently merged WKWebview changes of this library, but every time I call `ytPlayer.load(withVideoId: "...", playerVars: ...)`, my safari opens with my app's bundle id as the URL, making the video never load, and kicking the user out of the app.

Is anyone else facing this? Are there any workarounds for now?

I attached a sample app that shows the issue in action, when you try to load a video into the YTPlayerView:
[SampleYTPlayerApp.zip](https://github.com/youtube/youtube-ios-player-helper/files/4616264/SampleYTPlayerApp.zip)

Update: Turns out this happens on the Simulator and not when running on real devices. Is there any explanation for this? Should we be worried of it happening to any of our users?

Update 2: Its still happening when I run my app on a real device, so unfortunately this is still an issue.

**Comment by rcvrgs** [comment] 2020-05-13 18:05
Thank you for filing this issue. We are going to be trying to reproduce the issue in our side.

**Comment by L4grange** [comment] 2020-05-13 18:16
Thank you for taking the time to review this @rcvrgs , I am able to reproduce this on the iPhone 11 Pro Max iOS 13.4.1 Simulator in Xcode 11.4.1 on the sample project.

On my real iPhone 7 Plus, the sample project works properly, however, my production app exhibits the behaviour described above, using the same pod as in the sample app. (`pod "youtube-ios-player-helper", :git => 'https://github.com/youtube/youtube-ios-player-helper.git'`)

Let me know if you need any more information.

**Comment by Amin-Rehman** [comment] 2020-05-28 21:12
Hey folks! any updates when the fixes will be merged? thanks!

**Comment by odapivot** [comment] 2020-06-03 07:21
I think that the current implementation is a bug because a site of that domain is not required separately when naming the bundle ID.
I think we should return to seeing the origin parameter.

**Comment by rcvrgs** [comment] 2020-06-10 23:35
This issue was fixed by PR #377. The new pod 1.0.0 includes the fix.

**Comment by todd-patterson** [comment] 2020-06-11 02:16
As @rcvrgs mentioned, please update to the 1.0.0 release -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0

**Closed by todd-patterson** 2020-06-11 02:16 UTC

**Comment by L4grange** [comment] 2020-06-12 08:15
Thank you for this release! The issue is has been fixed, and we'll be releasing an update with this pod installed.
There are some new issues (with the videoURL function of the player, but I'll open another issue for them)
