### ISSUE TITLE
opens safari instead of loading the video,  Why?

### ISSUE THREAD

**Issue by YYHNobug** [youtube/youtube-ios-player-helper#375] opened 2020-05-15 08:58 UTC
opens safari instead of loading the video, Why?   

bundleId error?

**Comment by rcvrgs** [comment] 2020-05-20 20:22
Duplicate of #374. Follow that issue instead. 

Closing this one.

**Comment by todd-patterson** [comment] 2020-06-11 02:15
Should be fixed in the official 1.0.0 release -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0

Please update to that version.

**Closed by todd-patterson** 2020-06-11 02:15 UTC
